# backend/Dockerfile
FROM python:3.11-slim

WORKDIR /app

# Instala bibliotecas do sistema
RUN apt-get update && apt-get install -y libpq-dev gcc

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["gunicorn", "galileu_project.wsgi:application", "--bind", "0.0.0.0:8000"]